Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView, LoginView, LogoutView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace="items")),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('accounts/', include('allauth.urls')),

    # Password reset form
    path('password-reset/', PasswordResetView.as_view(template_name="registration/password_reset.html"),
         name="password_reset"),

    # Email sent success message
    path('password-reset-sent/', PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
         name="password_reset_done"),

    # link to password reset page
    path('password-reset-confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name="password_reset_confirm"),

    # Pwd changed successfully message
    path('password-reset-completed/',
         PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
         name="password_reset_complete"),

]

accounts/urls.py
from django.urls import path
from .views import UserCreateView, UserDetailView, UserUpdateView, PwdChangeView, CreateAddressView, UpdateAddressView, \
    CheckoutView, remove_address, load_district, load_ward, order_confirmation
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True),
         name="login"),
    path('dang-xuat/', LogoutView.as_view(), name='logout'),
    path('dang-ky/', UserCreateView.as_view(), name="signup"),
    path('thong-tin-ca-nhan/', UserDetailView.as_view(), name="profile"),
    path('cap-nhat-thong-tin/', UserUpdateView.as_view(), name="update"),
    path('thay-doi-mat-khau/', PwdChangeView.as_view(), name="pwd-change"),
    path('them-dia-chi/', CreateAddressView.as_view(), name="new-address"),
    path('cap-nhat-dia-chi/<pk>', UpdateAddressView.as_view(), name="update-address"),
    path('remove-address/<pk>', remove_address, name="remove-address"),
    path('ajax/load-districts/', load_district, name="ajax-load-districts"),
    path('ajax/load-wards/', load_ward, name="ajax-load-wards"),
    path('thanh-toan/', CheckoutView.as_view(), name="checkout"),
    path('order_confirmation/', order_confirmation, name='order_confirmation')
]

items/urls.py
from django.conf.urls.static import static
from django.urls import path

from Ecommerce import settings
from .views import *

app_name = 'items'

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path("chi-tiet-san-pham/<slug>/", ItemDetailView, name="details"),
                  path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
                  path('gio-hang/', CartView.as_view(), name='cart'),
                  path('tim-kiem/', item_search_view, name='search'),
                  path('danh-muc/<pk>', filter_by_category, name='filter-by-cate'),
                  path('remove-from-cart/<slug>/<size>', remove_from_cart, name='remove-from-cart'),
                  path('chi-tiet-don-hang/<pk>', OrderDetailView.as_view(), name='order-details'),
                  path('don-hang/', OrderListView.as_view(), name='orders'),
                  path('don-hang/dang-xu-ly/', OrderFilter, name='order-filter'),
                  path('don-hang/<state>', OrderFilter, name='order-filter'),
                  path('order-process-done/<pk>', OrderProcessDone, name='order-process-done'),
                  path('cancel-order/<pk>', cancel_order, name='cancel-order'),
                  path('remove-single-from-cart/<slug>/<size>/', remove_single_item_from_cart,
                       name='remove-single-from-cart'),
                  path('increase-quantity/<slug>/<size>/', increase_quantity, name='increase-quantity'),
                  path('aboutus', aboutus, name='aboutus'),
                  path('thanks', thanks, name='thanks')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.db.models import CharField
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model

from accounts.models import Address

# Create your models here.

User = get_user_model()


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Item(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    discount_price = models.IntegerField(blank=True, null=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='media/item-images', null=True, blank=True)
    ram = models.TextField(blank=True)
    chip = models.TextField(blank=True)
    vga = models.TextField(blank=True)
    memory = models.TextField(blank=True)
    pin = models.TextField(blank=True)
    weight = models.TextField(blank=True)
    hdh = models.TextField(blank=True)
    display = models.TextField(blank=True)
    port = models.TextField(blank=True)
    webcam = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Item, self).save(*args, **kwargs)

    def item_formated_price(self):
        return f"{self.price:,}đ"

    def item_formated_discount_price(self):
        return f"{self.discount_price:,}đ"

    def get_final_item_formated_price(self):
        return self.item_formated_discount_price() if self.discount_price else self.item_formated_price()

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ['id']


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/item-images')

    def __str__(self):
        return self.item.name


class OrderItem(models.Model):
    item = models.ForeignKey("Item", on_delete=models.CASCADE)
    size = models.CharField(max_length=300, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1)

    def get_final_price2(self):
        return f"{self.item.discount_price:,}d" if self.item.discount_price else f"{self.item.price:,}đ"

    def get_final_price(self):
        return self.item.discount_price if self.item.discount_price else self.item.price

    def get_item_total(self):
        total = self.get_final_price() * self.quantity
        return total

    def get_item_total_formated(self):
        return f"{self.get_item_total():,}đ"

    def __str__(self) -> str:
        return f"{self.item.name}({self.size})"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField("OrderItem")
    create_date = models.DateTimeField(auto_now=timezone.now)
    order_date = models.DateTimeField(blank=True, null=True)
    order_state = models.BooleanField(default=False)
    order_total = models.PositiveIntegerField(default=0, blank=True, null=True)

    shipping_address = models.ForeignKey(Address, blank=True, null=True, on_delete=models.CASCADE)
    process = models.BooleanField(default=None, blank=True, null=True)
    payment_method = models.CharField(max_length=64, blank=True, null=True)

    def get_order_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_item_total()
        return f"{total:,}đ"

    def set_order_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_item_total()
        self.order_total = total
        self.save()

    def __str__(self) -> str:
        return f"Order No.{self.pk}--Username:{self.user.username}"

items/forms.py
from django import forms
from django.forms import widgets

from items.models import Item

colors = (
    ('Đen', 'Đen'),
)
PAYMENT_CHOICES = (
    ('IB', 'Internet Banking'),
    ('C', 'COD')
)


class OrderItemForm(forms.Form):
    item_color = forms.ChoiceField(choices=colors, widget=forms.RadioSelect(attrs={'require': True}))

items/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
# from django.http import JsonResponse


from .forms import OrderItemForm
from .models import Item, Order, OrderItem, Category, ItemImage


class HomeView(ListView):
    paginate_by = 10
    template_name = 'index.html'
    model = Item
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context.update({
            "categories": categories
        })
        return context


class CartView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        order_qs = Order.objects.filter(user=self.request.user, order_state=False)
        if order_qs.exists():
            order = order_qs[0]
            context = {'order': order}
            return render(self.request, "items/cart.html", context)
        else:
            return render(self.request, 'items/cart.html', )


def slider_view(request, id):
    item = get_object_or_404(Item, id=id)
    photos = ItemImage.objects.filter(item=item)
    return render(request, 'templates/slider.html', {
        'item': item,
        'photos': photos
    })


def item_search_view(request):
    if request.method == "POST":
        print(request.POST)
        search = request.POST['searchBar']
        items = Item.objects.filter(name__icontains=search)
        context = {
            'items': items,

        }
        return render(request, 'items/item_search.html', context)
    elif request.method == "GET":
        return redirect("items:filter-by-cate")


def filter_by_category(request, pk):
    items = Item.objects.filter(categories_id=pk)
    context = {
        'items': items
    }
    return render(request, 'items/item_search.html', context)


class OrderListView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            order_qs = Order.objects.filter(order_state=True).order_by("-order_date")
            context = {"orders": order_qs}
            return render(self.request, "orders/order_list.html", context)
        else:
            order_qs = Order.objects.filter(user=self.request.user, order_state=True).order_by("-order_date")
            context = {"orders": order_qs}
            return render(self.request, "orders/order_list.html", context)


@login_required
def OrderFilter(request, state=None):
    if request.user.is_superuser:
        order_qs = Order.objects.filter(order_state=True, process=state).order_by("-order_date")
        context = {"orders": order_qs}
        return render(request, "orders/order_list.html", context)
    else:
        order_qs = Order.objects.filter(user=request.user, order_state=True, process=state).order_by("-order_date")
        context = {"orders": order_qs}
        return render(request, "orders/order_list.html", context)


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    context_object_name = "order"
    template_name = 'orders/order_details.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.all()
        else:
            user = self.request.user
            return user.order_set.all()


# cập nhật trạng thái đơn hàng
@login_required
def OrderProcessDone(request, pk):
    if request.user.is_superuser:
        order_qs = Order.objects.filter(pk=pk, order_state=True)
        if order_qs.exists():
            order = order_qs[0]
            order.process = True
            order.save()
            return redirect("items:orders")
        return redirect("items:orders")
    else:
        return redirect("items:orders")


def cancel_order(request, pk):
    if request.user.is_superuser:
        order_qs = Order.objects.filter(pk=pk, order_state=True)
        if order_qs.exists():
            order = order_qs[0]
            order.process = False
            order.save()
            return redirect("items:orders")
        return redirect("items:orders")


def ItemDetailView(request, slug):
    if request.method == "GET":
        item = Item.objects.filter(slug=slug)[0]
        photos = ItemImage.objects.filter(item=item)
        form = OrderItemForm()
        context = {
            "item": item,
            "form": form,
            "photos": photos
        }
        return render(request, "items/item_details.html", context=context)

    elif request.method == "POST":

        if "size" in request.POST:
            return add_to_cart(request, slug)
        else:
            msg = f"Vui lòng chọn màu sản phẩm!"
            messages.error(request, msg)
            return redirect("items:details", slug=slug)


@login_required
def add_to_cart(request, slug):
    size = request.POST['size']
    order_qs = Order.objects.filter(user=request.user, order_state=False)
    item = get_object_or_404(Item, slug=slug)
    if order_qs.exists():
        order = order_qs[0]  # Lấy order đầu tiên nếu order_qs có giá trị

        # Tìm item tương ứng để lấy nếu k sẽ tạo OrderItem mới tương ứng
        order_item, _ = OrderItem.objects.get_or_create(item=item, order=order, size=size)

        if order.items.filter(item__slug=item.slug, size=size):
            # Nếu đã có Item 
            order_item.quantity += 1
            order_item.save()
            # order.save()
            order.set_order_total()
            msg = f"Đã thêm {item.name} vào giỏ hàng!"
            messages.info(request, msg)
            return redirect("items:details", slug=slug)
        else:
            order.items.add(order_item)
            # order.save()
            order.set_order_total()

            msg = f"Đã thêm {item.name} vào giỏ hàng!"
            messages.info(request, msg)
            return redirect("items:details", slug=slug)
    else:
        order_item = OrderItem.objects.create(item=item, size=size)
        order = Order.objects.create(user=request.user)
        order.items.add(order_item)
        order.set_order_total()
        msg = f"Added {item.name} to  your cart!"
        messages.info(request, msg)
        return redirect("items:details", slug=slug)


@login_required
def remove_from_cart(request, slug, size):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, order_state=False)

    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug):

            # lấy danh sách order_item theo item, order, size
            order_item_qs = OrderItem.objects.filter(item=item, order=order, size=size)

            if order_item_qs.exists():
                order_item = order_item_qs[0]
                msg = f'Đã xóa {order_item.item.name} khỏi giỏ hàng.'
                order.items.remove(order_item)
                order_item.delete()
                messages.warning(request, msg)
                return redirect("items:cart")
            else:
                messages.warning(request, 'Item not in your cart.')
                return redirect("items:cart")


@login_required
def remove_single_item_from_cart(request, slug, size):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, order_state=False)

    if order_qs.exists():
        order = order_qs[0]
        order_item, _ = OrderItem.objects.get_or_create(item=item, order=order, size=size)

        if order.items.filter(item__slug=item.slug):
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                return redirect("items:cart")
            else:
                order_item.delete()
                return redirect("items:cart")


@login_required
def increase_quantity(request, slug, size):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, order_state=False)
    if order_qs.exists():
        order = order_qs[0]
        order_item, _ = OrderItem.objects.get_or_create(item=item, order=order, size=size)
        order_item.quantity += 1
        order_item.save()
        return redirect("items:cart")
    else:
        return redirect("items:cart")


def aboutus(request):
    return render(request, 'AboutUs.html')


def thanks(request):
    return render(request, 'thanks.html')

items/templates/items/cart.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block messages %}
    {% if messages %}
        {% for msg in messages %}
        <div role="alert" class="w-full flex justify-center font-semibold m-4">
        <span class="w-2/3 text-center
        {% if msg.tags == 'error' %}
            bg-white text-red-600 border-2 border-red-400
        {% else %}
            text-green-500 border-2 border-green-500
        {% endif %}
        rounded-full p-4">{{msg}}</span>
        </div>
        {% endfor %}
    {% endif %}
{% endblock messages %}


{% block body_content %}



  <div class="container mx-auto mt-10 h-screen">
    <div class="flex shadow-md my-10">
      <div class="w-3/4 bg-white px-10 py-10">
        <div class="flex justify-between border-b pb-8">
          <h1 class="font-semibold text-2xl">Giỏ hàng</h1>
        </div>
        <div class="flex mt-10 mb-5">
          <h3 class="font-semibold text-gray-600 text-2xs uppercase w-2/5">Chi tiết sản phẩm</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Số lượng</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Giá</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Tổng</h3>
        </div>
          {% for order_item in order.items.all %}
        <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5 border-r">
          <div class="flex w-2/5"> <!-- product -->
              {% if order_item.item.image %}
                    <img  src="{{order_item.item.image.url}}" class="w-16 h-16" alt="">
                    {% endif %}
            <div class="w-20">
            </div>
            <div class="flex flex-col justify-between ml-4 flex-grow">
              <span class="font-bold text-xl">{{order_item.item.name}}</span>
              <span class="text-red-500 text-xs">{{order_item.item.categories}}</span>
              <a href="{% url 'items:remove-from-cart' order_item.item.slug order_item.size %}" class="font-semibold hover:text-red-500 text-gray-500 text-2xs ">Xóa</a>
            </div>
          </div>
          <div class="flex justify-center w-1/5">
              <a href="{% url 'items:remove-single-from-cart' order_item.item.slug order_item.size %}" class="pt-1">
            <svg class="fill-current text-gray-600 w-3" viewBox="0 0 448 512"><path d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/>
            </svg>
              </a>

            <input class="mx-2 border text-center w-8" type="text" value="{{order_item.quantity}}">
                <a href="{% url 'items:increase-quantity' order_item.item.slug order_item.size %}" class="pt-1">
            <svg class="fill-current text-gray-600 w-3" viewBox="0 0 448 512">
              <path d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/>
            </svg>
                </a>
          </div>
          <span class="text-center w-1/5 font-semibold text-xl">{{order_item.get_final_price2}}</span>
          <span class="text-center w-1/5 font-semibold text-xl">{{order_item.get_item_total_formated}}</span>
        </div>
        {% endfor %}

        <a href="{% url 'items:home' %}" class="flex font-semibold text-indigo-600 text-sm mt-10">

          <svg class="fill-current mr-2 text-indigo-600 w-4" viewBox="0 0 448 512"><path d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"/></svg>
          Tiếp tục mua sắm
        </a>
      </div>

      <div id="summary" class="w-1/4 px-8 py-10 grid grid-cols-1 gap-4 flex justify-center">



        <div class=" mt-20 place-self-end ">
          <div class="flex font-semibold justify-between py-6 text-sm uppercase col-span-4 text-xl">
            <span class="mr-4 mb-5">Tổng đơn hàng: </span>
            <span>{{order.get_order_total}}</span>
          </div>
          <button class="bg-indigo-500 font-semibold hover:bg-indigo-600 py-3 text-sm text-white uppercase w-full"><a href="{% url 'accounts:checkout' %}"> Checkout</a></button>
        </div>
      </div>

    </div>
  </div>




{% endblock body_content %}

items/templates/items/item_search.html
{% extends "base.html" %}
{% load static %}
{% block body_content %}

    <style>
        .work-sans {
            font-family: 'Work Sans', sans-serif;
        }

        #menu-toggle:checked + #menu {
            display: block;
        }

        .hover\:grow {
            transition: all 0.3s;
            transform: scale(1);
        }

        .hover\:grow:hover {
            transform: scale(1.02);
        }

        .carousel-open:checked + .carousel-item {
            position: static;
            opacity: 100;
        }

        .carousel-item {
            -webkit-transition: opacity 0.6s ease-out;
            transition: opacity 0.6s ease-out;
        }

        #carousel-1:checked ~ .control-1,
        #carousel-2:checked ~ .control-2,
        #carousel-3:checked ~ .control-3 {
            display: block;
        }

        .carousel-indicators {
            list-style: none;
            margin: 0;
            padding: 0;
            position: absolute;
            bottom: 2%;
            left: 0;
            right: 0;
            text-align: center;
            z-index: 10;
        }

        #carousel-1:checked ~ .control-1 ~ .carousel-indicators li:nth-child(1) .carousel-bullet,
        #carousel-2:checked ~ .control-2 ~ .carousel-indicators li:nth-child(2) .carousel-bullet,
        #carousel-3:checked ~ .control-3 ~ .carousel-indicators li:nth-child(3) .carousel-bullet {
            color: #000;
            /*Set to match the Tailwind colour you want the active one to be */
        }
    </style>


    <section class="bg-white py-8">
  <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
        <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
            <nav id="store" class="w-full z-30 top-0 px-6 py-1  text-xl">
                <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 py-3">
                    <a class="uppercase tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-xl " href="{% url 'items:home' %}">
				Store
			        </a>

                    {{ item.chip }}
                    <div class="flex items-center" id="store-nav-content text-2xl">
                        <button class="pl-3 inline-block no-underline hover:text-black">
                            <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24">
                                <path d="M7 11H17V13H7zM4 7H20V9H4zM10 15H14V17H10z" />
                            </svg>
                        </button>

               <div  id="searchBox" >
               <form action="{% url 'items:search' %}" method="POST">
                {% csrf_token %}
                 <div class="flex items-center max-w-md mx-auto bg-gray-200 rounded-lg ">
                     <div class="w-full">
                     <input id="searchBar" name="searchBar" type="search" class="w-full px-4 py-1 text-gray-800  focus:outline-none bg-gray-200"
                placeholder="search">
                    </div>
                 <div>
            <button  id="search" type="submit" class="flex items-center bg-blue-500 justify-center w-12 h-12 text-white rounded-r-lg"  >
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </button>
                 </div>
                </div>
            </form>
               </div>


               </div>
              </div>
            </nav>


                 {% for item in items %}

            <div class="w-full md:w-1/3 xl:w-1/4 p-6 flex flex-col">

                  <a href="{% url 'items:details' item.slug %}" class="">
                        {% if item.image %}
                    <img class="hover:grow hover:shadow-lg" src="{{item.image.url}}">
                      {% endif %}
                    <div class="pt-3 flex items-center justify-between">
                        <p class="text-3xs font-bold">{{item.name}}</p>
                        <svg class="h-6 w-6 fill-current text-gray-500 hover:text-black" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M12,4.595c-1.104-1.006-2.512-1.558-3.996-1.558c-1.578,0-3.072,0.623-4.213,1.758c-2.353,2.363-2.352,6.059,0.002,8.412 l7.332,7.332c0.17,0.299,0.498,0.492,0.875,0.492c0.322,0,0.609-0.163,0.792-0.409l7.415-7.415 c2.354-2.354,2.354-6.049-0.002-8.416c-1.137-1.131-2.631-1.754-4.209-1.754C14.513,3.037,13.104,3.589,12,4.595z M18.791,6.205 c1.563,1.571,1.564,4.025,0.002,5.588L12,18.586l-6.793-6.793C3.645,10.23,3.646,7.776,5.205,6.209 c0.76-0.756,1.754-1.172,2.799-1.172s2.035,0.416,2.789,1.17l0.5,0.5c0.391,0.391,1.023,0.391,1.414,0l0.5-0.5 C14.719,4.698,17.281,4.702,18.791,6.205z" />
                        </svg>
                    </div>
                      {% if item.discount_price %}
                    <p class="pt-1 text-2xs text-gray-900">
                              <label class="text-2xs text-center text-black font-semibold">{{item.item_formated_discount_price}}</label>
                              <del class="text-lg text-center text-red-500 font-semibold">{{item.item_formated_price}}</del>
                              {% else %}
                              <label class="text-2xs text-center text-black font-semibold">{{item.item_formated_price}}</label>
                             </p>
                       {% endif %}
                </a>
            </div>
         {% endfor %}
     </div>

            </div>

    </section>

{% endblock body_content %}
{% block script %}


<script>
  //Get the button
  var mybutton = document.getElementById("btnToTop");
  var mybutton2 = document.getElementById("btnToTop2");

  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function() {scrollFunction()};

  function scrollFunction() {
    if (document.body.scrollTop > 500 || document.documentElement.scrollTop > 500) {
      mybutton.style.display = "block";
      mybutton2.style.display = "block";
    } else {
      mybutton.style.display = "none";
      mybutton2.style.display = "none";
    }
  }

  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
  </script>

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script>
  <script>
    var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                // $('.loading').show();
            },
            onAfterPageLoad: function () {
                // $('.loading').hide();
            }
        });
  </script>
<script>
        $(function () {
            var availableTags = [
                {% for item in items %}
            "{{item.name}}",
            {% endfor %}
    ];
        $("#searchBar").autocomplete({
            source: availableTags
        });
  } );
    </script>
{% endblock script %}

items/templates/items/item_size.html
{% block body_content %}

   <div class="flex items-center pb-2 border-t-2 border-gray-100 mb-5 ">
          <div class="flex">
              <form method="POST" id="order_item_form" class = ' flex flex-row items-center font-semibold m-2'>
        {% csrf_token %}
        {% for value, name in form.fields.item_color.choices %}
          <input type="radio" name='size' id='{{name}}' value='{{value}}' checked="checked" class="appearance-none">
        {% endfor %}
        {{form.quantity}}
    </form>

          </div>
          <div class="flex ml-6 items-center">
            <div class="relative">
            </div>
          </div>
        </div>
          <button onclick="myFunction()" class="active:bg-violet-700 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Thêm vào giỏ hàng</button>


{% endblock body_content %}
{% block script %}
<script>
  function myFunction() {
      document.getElementById("order_item_form").submit();
  }
</script>
{% endblock script %}