Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView, LoginView, LogoutView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace="items")),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('accounts/', include('allauth.urls')),

    # Password reset form
    path('password-reset/', PasswordResetView.as_view(template_name="registration/password_reset.html"),
         name="password_reset"),

    # Email sent success message
    path('password-reset-sent/', PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
         name="password_reset_done"),

    # link to password reset page
    path('password-reset-confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name="password_reset_confirm"),

    # Pwd changed successfully message
    path('password-reset-completed/',
         PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
         name="password_reset_complete"),

]

items/urls.py
from django.conf.urls.static import static
from django.urls import path

from Ecommerce import settings
from .views import *

app_name = 'items'

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path("chi-tiet-san-pham/<slug>/", ItemDetailView, name="details"),
                  path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
                  path('gio-hang/', CartView.as_view(), name='cart'),
                  path('tim-kiem/', item_search_view, name='search'),
                  path('danh-muc/<pk>', filter_by_category, name='filter-by-cate'),
                  path('remove-from-cart/<slug>/<size>', remove_from_cart, name='remove-from-cart'),
                  path('chi-tiet-don-hang/<pk>', OrderDetailView.as_view(), name='order-details'),
                  path('don-hang/', OrderListView.as_view(), name='orders'),
                  path('don-hang/dang-xu-ly/', OrderFilter, name='order-filter'),
                  path('don-hang/<state>', OrderFilter, name='order-filter'),
                  path('order-process-done/<pk>', OrderProcessDone, name='order-process-done'),
                  path('cancel-order/<pk>', cancel_order, name='cancel-order'),
                  path('remove-single-from-cart/<slug>/<size>/', remove_single_item_from_cart,
                       name='remove-single-from-cart'),
                  path('increase-quantity/<slug>/<size>/', increase_quantity, name='increase-quantity'),
                  path('aboutus', aboutus, name='aboutus'),
                  path('thanks', thanks, name='thanks')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.db.models import CharField
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth import get_user_model

from accounts.models import Address

# Create your models here.

User = get_user_model()


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Item(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    discount_price = models.IntegerField(blank=True, null=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='media/item-images', null=True, blank=True)
    ram = models.TextField(blank=True)
    chip = models.TextField(blank=True)
    vga = models.TextField(blank=True)
    memory = models.TextField(blank=True)
    pin = models.TextField(blank=True)
    weight = models.TextField(blank=True)
    hdh = models.TextField(blank=True)
    display = models.TextField(blank=True)
    port = models.TextField(blank=True)
    webcam = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Item, self).save(*args, **kwargs)

    def item_formated_price(self):
        return f"{self.price:,}đ"

    def item_formated_discount_price(self):
        return f"{self.discount_price:,}đ"

    def get_final_item_formated_price(self):
        return self.item_formated_discount_price() if self.discount_price else self.item_formated_price()

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ['id']


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='media/item-images')

    def __str__(self):
        return self.item.name


class OrderItem(models.Model):
    item = models.ForeignKey("Item", on_delete=models.CASCADE)
    size = models.CharField(max_length=300, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1)

    def get_final_price2(self):
        return f"{self.item.discount_price:,}d" if self.item.discount_price else f"{self.item.price:,}đ"

    def get_final_price(self):
        return self.item.discount_price if self.item.discount_price else self.item.price

    def get_item_total(self):
        total = self.get_final_price() * self.quantity
        return total

    def get_item_total_formated(self):
        return f"{self.get_item_total():,}đ"

    def __str__(self) -> str:
        return f"{self.item.name}({self.size})"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField("OrderItem")
    create_date = models.DateTimeField(auto_now=timezone.now)
    order_date = models.DateTimeField(blank=True, null=True)
    order_state = models.BooleanField(default=False)
    order_total = models.PositiveIntegerField(default=0, blank=True, null=True)

    shipping_address = models.ForeignKey(Address, blank=True, null=True, on_delete=models.CASCADE)
    process = models.BooleanField(default=None, blank=True, null=True)
    payment_method = models.CharField(max_length=64, blank=True, null=True)

    def get_order_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_item_total()
        return f"{total:,}đ"

    def set_order_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_item_total()
        self.order_total = total
        self.save()

    def __str__(self) -> str:
        return f"Order No.{self.pk}--Username:{self.user.username}"

items/forms.py
from django import forms
from django.forms import widgets

from items.models import Item

colors = (
    ('Đen', 'Đen'),
)
PAYMENT_CHOICES = (
    ('IB', 'Internet Banking'),
    ('C', 'COD')
)


class OrderItemForm(forms.Form):
    item_color = forms.ChoiceField(choices=colors, widget=forms.RadioSelect(attrs={'require': True}))

items/views.py
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
# from django.http import JsonResponse


from .forms import OrderItemForm
from .models import Item, Order, OrderItem, Category, ItemImage


class HomeView(ListView):
    paginate_by = 10
    template_name = 'index.html'
    model = Item
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context.update({
            "categories": categories
        })
        return context


class CartView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        order_qs = Order.objects.filter(user=self.request.user, order_state=False)
        if order_qs.exists():
            order = order_qs[0]
            context = {'order': order}
            return render(self.request, "items/cart.html", context)
        else:
            return render(self.request, 'items/cart.html', )


def slider_view(request, id):
    item = get_object_or_404(Item, id=id)
    photos = ItemImage.objects.filter(item=item)
    return render(request, 'templates/slider.html', {
        'item': item,
        'photos': photos
    })


def item_search_view(request):
    if request.method == "POST":
        print(request.POST)
        search = request.POST['searchBar']
        items = Item.objects.filter(name__icontains=search)
        context = {
            'items': items,

        }
        return render(request, 'items/item_search.html', context)
    elif request.method == "GET":
        return redirect("items:filter-by-cate")


def filter_by_category(request, pk):
    items = Item.objects.filter(categories_id=pk)
    context = {
        'items': items
    }
    return render(request, 'items/item_search.html', context)


class OrderListView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        if self.request.user.is_superuser:
            order_qs = Order.objects.filter(order_state=True).order_by("-order_date")
            context = {"orders": order_qs}
            return render(self.request, "orders/order_list.html", context)
        else:
            order_qs = Order.objects.filter(user=self.request.user, order_state=True).order_by("-order_date")
            context = {"orders": order_qs}
            return render(self.request, "orders/order_list.html", context)


@login_required
def OrderFilter(request, state=None):
    if request.user.is_superuser:
        order_qs = Order.objects.filter(order_state=True, process=state).order_by("-order_date")
        context = {"orders": order_qs}
        return render(request, "orders/order_list.html", context)
    else:
        order_qs = Order.objects.filter(user=request.user, order_state=True, process=state).order_by("-order_date")
        context = {"orders": order_qs}
        return render(request, "orders/order_list.html", context)


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    context_object_name = "order"
    template_name = 'orders/order_details.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Order.objects.all()
        else:
            user = self.request.user
            return user.order_set.all()


# cập nhật trạng thái đơn hàng
@login_required
def OrderProcessDone(request, pk):
    if request.user.is_superuser:
        order_qs = Order.objects.filter(pk=pk, order_state=True)
        if order_qs.exists():
            order = order_qs[0]
            order.process = True
            order.save()
            return redirect("items:orders")
        return redirect("items:orders")
    else:
        return redirect("items:orders")


def cancel_order(request, pk):
    if request.user.is_superuser:
        order_qs = Order.objects.filter(pk=pk, order_state=True)
        if order_qs.exists():
            order = order_qs[0]
            order.process = False
            order.save()
            return redirect("items:orders")
        return redirect("items:orders")


def ItemDetailView(request, slug):
    if request.method == "GET":
        item = Item.objects.filter(slug=slug)[0]
        photos = ItemImage.objects.filter(item=item)
        form = OrderItemForm()
        context = {
            "item": item,
            "form": form,
            "photos": photos
        }
        return render(request, "items/item_details.html", context=context)

    elif request.method == "POST":

        if "size" in request.POST:
            return add_to_cart(request, slug)
        else:
            msg = f"Vui lòng chọn màu sản phẩm!"
            messages.error(request, msg)
            return redirect("items:details", slug=slug)


@login_required
def add_to_cart(request, slug):
    size = request.POST['size']
    order_qs = Order.objects.filter(user=request.user, order_state=False)
    item = get_object_or_404(Item, slug=slug)
    if order_qs.exists():
        order = order_qs[0]  # Lấy order đầu tiên nếu order_qs có giá trị

        # Tìm item tương ứng để lấy nếu k sẽ tạo OrderItem mới tương ứng
        order_item, _ = OrderItem.objects.get_or_create(item=item, order=order, size=size)

        if order.items.filter(item__slug=item.slug, size=size):
            # Nếu đã có Item 
            order_item.quantity += 1
            order_item.save()
            # order.save()
            order.set_order_total()
            msg = f"Đã thêm {item.name} vào giỏ hàng!"
            messages.info(request, msg)
            return redirect("items:details", slug=slug)
        else:
            order.items.add(order_item)
            # order.save()
            order.set_order_total()

            msg = f"Đã thêm {item.name} vào giỏ hàng!"
            messages.info(request, msg)
            return redirect("items:details", slug=slug)
    else:
        order_item = OrderItem.objects.create(item=item, size=size)
        order = Order.objects.create(user=request.user)
        order.items.add(order_item)
        order.set_order_total()
        msg = f"Added {item.name} to  your cart!"
        messages.info(request, msg)
        return redirect("items:details", slug=slug)


@login_required
def remove_from_cart(request, slug, size):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, order_state=False)

    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug):

            # lấy danh sách order_item theo item, order, size
            order_item_qs = OrderItem.objects.filter(item=item, order=order, size=size)

            if order_item_qs.exists():
                order_item = order_item_qs[0]
                msg = f'Đã xóa {order_item.item.name} khỏi giỏ hàng.'
                order.items.remove(order_item)
                order_item.delete()
                messages.warning(request, msg)
                return redirect("items:cart")
            else:
                messages.warning(request, 'Item not in your cart.')
                return redirect("items:cart")


@login_required
def remove_single_item_from_cart(request, slug, size):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, order_state=False)

    if order_qs.exists():
        order = order_qs[0]
        order_item, _ = OrderItem.objects.get_or_create(item=item, order=order, size=size)

        if order.items.filter(item__slug=item.slug):
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                return redirect("items:cart")
            else:
                order_item.delete()
                return redirect("items:cart")


@login_required
def increase_quantity(request, slug, size):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, order_state=False)
    if order_qs.exists():
        order = order_qs[0]
        order_item, _ = OrderItem.objects.get_or_create(item=item, order=order, size=size)
        order_item.quantity += 1
        order_item.save()
        return redirect("items:cart")
    else:
        return redirect("items:cart")


def aboutus(request):
    return render(request, 'AboutUs.html')


def thanks(request):
    return render(request, 'thanks.html')

items/templates/orders/order_details.html
{% extends "base.html" %}
{% block body_content %}
<div class="flex justify-center items-center md:mt-16">
    <div class="flex flex-col justify-center md:flex-col w-full md:w-4/5 xl:w-3/5 2xl:w-3/5 border bg-white rounded-xl">
        <h1 class="text-center font-semibol text-3xl p-4">Chi tiết đơn hàng</h1>
        
        <table>
            <tr>
                <th class="text-center text-black p-8">#</th>
                <th class="text-center text-black p-8">Ảnh</th>
                <th class="text-center text-black p-8">Tên</th>
                <th class="text-center text-black p-8">Giá</th>
                <th class="text-center text-black p-8">Số lượng</th>
                <th class="text-center text-black p-8">Tổng</th>
            </tr>
            {% for order_item in order.items.all %}
            <tr>
                <td class="text-center pb-4">{{ forloop.counter }}</td>
                <td class="text-center pb-4">{% if order_item.item.image %}<img  src="{{order_item.item.image.url}}"  class="w-16 h-16" alt="">{% endif %}</td>
                <td class="text-center pb-4"><a class = "hover:underline" href="{% url 'items:details' order_item.item.slug %}">{{order_item.item.name}}({{order_item.size}}) </a>  </td>
                <td class="text-center pb-4">{{order_item.item.get_final_item_formated_price}}</td>
                <td class="text-center pb-4">{{order_item.quantity}}</td>
                <td class="text-center pb-4">{{order_item.get_item_total_formated}}</td>
            </tr>
              
            {% endfor %}
            <tr  class="p-4">
                <td colspan="4"></td>
                <td class="text-center text-2xl">Tổng: </td>
                <td class="text-center text-2xl">{{order.get_order_total}}</td>
            </tr>
            <tr  class="p-8">
                <td colspan="2"></td>
                <td colspan="2"></td>
                <td class="text-center text-2xl">PTTT: </td>
                <td class="text-center text-2xl">{{order.payment_method}}</td>
            </tr>
        </table>
        <div class="flex {% if user.is_superuser %}justify-between{% else %} justify-end {% endif %} items-center p-8">
            {% if user.is_superuser %}
            <a href="{% url 'items:order-process-done' order.pk %}" class="border-2 hover:bg-black hover:text-white text-black bg-transparent font-semibold p-4 rounded-xl">Hoàn tất đơn hàng</a>
            <a href="{% url 'items:cancel-order' order.pk %}" class="border-2 hover:bg-black hover:text-white text-black bg-transparent font-semibold p-4 rounded-xl">Hủy đơn hàng</a>
            {% endif %}
            <div>
                <p>Họ tên: {{order.shipping_address.full_name}}</p>
                <p>Số điện thoại: {{order.shipping_address.phone}}</p>
                <p>Địa chỉ: {{order.shipping_address.home}}{% if order.shipping_address.ward is not None %}
                {{order.shipping_address.ward}}, {% endif %} 
                {{order.shipping_address.district}}, 
                {{order.shipping_address.city}}</p>
            </div>
        </div>
    </div>
  </div>
{% endblock body_content %}

items/templates/orders/order_list.html
{% extends "base.html" %}
{% block body_content %}
<div class="flex justify-center items-center md:mt-16">
    <div class="flex flex-col justify-center overflow-x-auto md:flex-col w-full md:w-4/5 xl:w-3/5 2xl:w-3/5 border bg-white rounded-xl">
        <table>
            <tr>
                <td colspan="5"></td>
                <td class="text-center text-black pt-4">
        Trạng thái: <a class = "hover:underline" href="{% url 'items:order-filter' 1 %}">Đã xong</a> | 
                    <a class = "hover:underline" href="{% url 'items:order-filter' 0 %}">Đã hủy</a> | 
                    <a class = "hover:underline" href="{% url 'items:order-filter' %}">Đang xử lý</a> | 
                    <a class = "hover:underline" href="{% url 'items:orders' %}">Tất cả</a></td>

            </tr>
            <tr>
                <th class="text-center text-black p-8">Mã</th>
                <th class="text-center text-black p-8">Ngày đặt</th>
                <th class="text-center text-black p-8">Họ tên</th>
                <th class="text-center text-black p-8">SĐT</th>
                <th class="text-center text-black p-8">Email</th>
                <th class="text-center text-black p-8">Trạng thái xử lý</th>
            </tr>
            {% for order in orders %}
            <tr>
                <td class="text-center pb-4"><a class = "hover:underline" href="{% url 'items:order-details' order.pk %}">Đơn hàng số {{order.pk}}</a></td>
                <td class="text-center pb-4">{{order.order_date | date:"d/m/Y h:i A"}}</td>
                <td class="text-center pb-4">{{order.shipping_address.full_name}}</td>
                <td class="text-center pb-4">{{order.shipping_address.phone}}</td>
                <td class="text-center pb-4">{{order.user.email}}</td>
                <td class="text-center pb-4">
                    {% if order.process == True %}
                      Hoàn thành
                    {% elif order.process == False %}
                      Đã Hủy
                    {% else %}
                      Đang xử lý
                    {% endif %}
                </td>
            </tr>
              
            {% endfor %}
        </table>
    </div>
  </div>
{% endblock body_content %}