Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView, LoginView, LogoutView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace="items")),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('accounts/', include('allauth.urls')),

    # Password reset form
    path('password-reset/', PasswordResetView.as_view(template_name="registration/password_reset.html"),
         name="password_reset"),

    # Email sent success message
    path('password-reset-sent/', PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
         name="password_reset_done"),

    # link to password reset page
    path('password-reset-confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name="password_reset_confirm"),

    # Pwd changed successfully message
    path('password-reset-completed/',
         PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
         name="password_reset_complete"),

]

accounts/urls.py
from django.urls import path
from .views import UserCreateView, UserDetailView, UserUpdateView, PwdChangeView, CreateAddressView, UpdateAddressView, \
    CheckoutView, remove_address, load_district, load_ward, order_confirmation
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [

    path('login/', LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True),
         name="login"),
    path('dang-xuat/', LogoutView.as_view(), name='logout'),
    path('dang-ky/', UserCreateView.as_view(), name="signup"),
    path('thong-tin-ca-nhan/', UserDetailView.as_view(), name="profile"),
    path('cap-nhat-thong-tin/', UserUpdateView.as_view(), name="update"),
    path('thay-doi-mat-khau/', PwdChangeView.as_view(), name="pwd-change"),
    path('them-dia-chi/', CreateAddressView.as_view(), name="new-address"),
    path('cap-nhat-dia-chi/<pk>', UpdateAddressView.as_view(), name="update-address"),
    path('remove-address/<pk>', remove_address, name="remove-address"),
    path('ajax/load-districts/', load_district, name="ajax-load-districts"),
    path('ajax/load-wards/', load_ward, name="ajax-load-wards"),
    path('thanh-toan/', CheckoutView.as_view(), name="checkout"),
    path('order_confirmation/', order_confirmation, name='order_confirmation')
]

items/urls.py
from django.conf.urls.static import static
from django.urls import path

from Ecommerce import settings
from .views import *

app_name = 'items'

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path("chi-tiet-san-pham/<slug>/", ItemDetailView, name="details"),
                  path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
                  path('gio-hang/', CartView.as_view(), name='cart'),
                  path('tim-kiem/', item_search_view, name='search'),
                  path('danh-muc/<pk>', filter_by_category, name='filter-by-cate'),
                  path('remove-from-cart/<slug>/<size>', remove_from_cart, name='remove-from-cart'),
                  path('chi-tiet-don-hang/<pk>', OrderDetailView.as_view(), name='order-details'),
                  path('don-hang/', OrderListView.as_view(), name='orders'),
                  path('don-hang/dang-xu-ly/', OrderFilter, name='order-filter'),
                  path('don-hang/<state>', OrderFilter, name='order-filter'),
                  path('order-process-done/<pk>', OrderProcessDone, name='order-process-done'),
                  path('cancel-order/<pk>', cancel_order, name='cancel-order'),
                  path('remove-single-from-cart/<slug>/<size>/', remove_single_item_from_cart,
                       name='remove-single-from-cart'),
                  path('increase-quantity/<slug>/<size>/', increase_quantity, name='increase-quantity'),
                  path('aboutus', aboutus, name='aboutus'),
                  path('thanks', thanks, name='thanks')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User, PermissionsMixin
from django.core.validators import RegexValidator


# Create your models here.

class User(User, PermissionsMixin):

    _meta = None

    def __str__(self):
        return self.username


User._meta.get_field('email')._unique = True
User._meta.get_field('email').blank = False
User._meta.get_field('email').null = False


class Address(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='addresses', on_delete=models.CASCADE)
    city = models.ForeignKey("City", on_delete=models.CASCADE)
    district = models.ForeignKey("District", on_delete=models.CASCADE)
    ward = models.ForeignKey("Ward", on_delete=models.CASCADE, blank=True, null=True)
    home = models.CharField(max_length=255, blank=False, null=False)
    full_name = models.CharField(max_length=255, blank=False, null=False, default="")
    phone = models.CharField(validators=[
        RegexValidator(regex=r'^\+?1?\d{9,10}$', message="Số điện thoại phải đúng định dạng '0123 456 789'."), ],
                             max_length=10, blank=False, null=False, default="")

    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.home} - phường/xã {self.ward}," \
               f" {self.district}, {self.city}"

    class Meta:
        verbose_name_plural = 'Addresses'


class City(models.Model):
    objects = None
    name = models.CharField(max_length=128, unique=True)
    code = models.CharField(max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'


class District(models.Model):
    city = models.ForeignKey(City, related_name='districts', on_delete=models.CASCADE)
    name = models.CharField(max_length=128)

    def __str__(self):
        return f" {self.name}" if self.name.split()[0] != 'Quận' else self.name


class Ward(models.Model):
    district = models.ForeignKey(District, related_name='wards', on_delete=models.CASCADE)
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls.base import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    PasswordChangeView,
)
from django.contrib.auth import get_user_model
from django.contrib import messages

from django.utils import timezone
from django.template.loader import render_to_string
from django.conf import settings
from django.core.mail import EmailMessage

from .forms import CreateUserForm, UserUpdateForm, UserPasswordChangeForm, AddressCreateForm, CheckOutForm
from .models import Address, City, District, Ward

from items.models import Order, OrderItem

User = get_user_model()


class UserCreateView(CreateView):
    form_class = CreateUserForm
    template_name = 'registration/signup.html'

    def get_success_url(self):
        return redirect("login")

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('items:home')
        return super(UserCreateView, self).get(request, *args, **kwargs)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = "user"
    template_name = "accounts/user_profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        address_qs = Address.objects.filter(user=self.request.user)
        context.update({
            'address_list': address_qs
        })
        return context

    def get_object(self, *args, **kwargs):
        return self.request.user


class UserUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserUpdateForm
    template_name = "accounts/user_info_update.html"

    def get_object(self, *args, **kwargs):
        return self.request.user

    def get_success_url(self):
        messages.info(self.request, "Updated")
        return reverse("accounts:profile", kwargs={'pk': self.object.pk})


class PwdChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = "registration/password_change.html"

    def get_object(self, *args, **kwargs):
        return self.request.user

    def get_success_url(self) -> str:
        messages.info(self.request, "Password Changed!")
        return reverse("accounts:profile", kwargs={'pk': self.request.user.pk})


class CreateAddressView(LoginRequiredMixin, CreateView):
    form_class = AddressCreateForm
    template_name = "addresses/address_create_form.html"
    success_url = reverse_lazy("accounts:profile")

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)


class UpdateAddressView(LoginRequiredMixin, UpdateView):
    form_class = AddressCreateForm
    template_name = "addresses/address_update.html"
    context_object_name = "address"
    success_url = reverse_lazy("accounts:profile")

    def get_queryset(self):
        return Address.objects.filter(user=self.request.user)


def remove_address(request, pk):
    address_qs = Address.objects.filter(user=request.user, pk=pk)
    if address_qs.exists():
        address = address_qs[0]
        address.delete()
    else:
        pass
    return redirect("accounts:profile")


def load_district(request):
    city_id = request.GET.get('city')
    districts = District.objects.filter(city_id=city_id).order_by('name')
    return render(request, 'addresses/districts_dropdown_list_options.html', {'districts': districts})


def load_ward(request):
    district_id = request.GET.get('district')
    wards = Ward.objects.filter(district_id=district_id).order_by('name')
    return render(request, 'addresses/ward_dropdown_list_options.html', {'wards': wards})


class CheckoutView(LoginRequiredMixin, View):

    def get(self, *args, **kwargs):
        form = CheckOutForm()
        context = {
            'form': form,
        }

        order_qs = Order.objects.filter(user=self.request.user, order_state=False)
        if order_qs.exists():
            order = order_qs[0]
            items = OrderItem.objects.filter(order=order_qs[0])
            context.update({
                'order': order,
            })
            # Lấy danh sách item của order sau đó thêm vào context
            if items.exists():
                context.update({
                    'items': items,
                })
                # Lấy danh sách địa chỉ giao hàng của user sau đó thêm vào context
                addresses = Address.objects.filter(user=self.request.user)
                if addresses.exists():
                    context.update({'addresses': addresses})
                return render(self.request, 'accounts/checkout.html', context)

            else:  # Nếu không có sản phẩm nào của order
                messages.error(self.request, "Không có sản phẩm trong giỏ hàng!")
                return redirect("items:cart")
        # Nếu không có order
        else:
            messages.error(self.request, "Không có sản phẩm trong giỏ hàng!")
            return redirect("items:cart")

    def post(self, *args, **kwargs):
        form = CheckOutForm(self.request.POST or None)
        # print(self.request.POST)
        if form.is_valid() and 'address' in self.request.POST:
            # print("form",form.cleaned_data)
            address_id = self.request.POST['address']
            address = get_object_or_404(Address, user=self.request.user, pk=address_id)
            order_qs = Order.objects.filter(user=self.request.user, order_state=False)
            if order_qs.exists():
                order = order_qs[0]
                order.shipping_address = address
                order.order_state = True
                order.order_date = timezone.now()
                order.payment_method = self.request.POST['payment_option']
                order.save()

                # Gửi mail thông báo tới user
                template = render_to_string('accounts/email_confirm.html',
                                            {'name': self.request.user.first_name + ' ' + self.request.user.last_name})
                email = EmailMessage(
                    'Thông báo tiếp nhận đơn hàng',
                    template,
                    settings.EMAIL_HOST_USER,
                    {self.request.user.email},
                )
                email.fail_silently = False
                email.send()

            return redirect('items:thanks')
        else:
            messages.error(self.request, "Vui lòng chọn địa chỉ giao hàng")
            return redirect('accounts:checkout')


def order_confirmation(request):
    order = Order.objects.get(pk=5)
    return render(request, 'accounts/email_confirm.html', {'oder': order})

accounts/templates/accounts/checkout.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block messages %}
    {% if messages %}
        {% for msg in messages %}
        <div role="alert" class="w-full flex justify-center font-semibold m-4">
        <span class="w-2/3 text-center
        {% if msg.tags == 'error' %} 
            bg-white text-red-600 border-2 border-red-400
        {% else %} 
            text-green-500 border-2 border-green-500
        {% endif %} 
        rounded-full p-4">{{msg}}</span>
        </div>
        {% endfor %}
    {% endif %}
{% endblock messages %}

{% block body_content %}

<div class="py-14 px-4 md:px-6 2xl:px-20 2xl:container 2xl:mx-auto">
  <div class="flex justify-start item-start space-y-2 flex-col">
    <h1 class="text-3xl dark:text-white lg:text-4xl font-semibold leading-7 lg:leading-9 text-gray-800">Order #13432</h1>
    <p class="text-base dark:text-gray-300 font-medium leading-6 text-gray-600 ml-3" id="current_date"></p>
  </div>
  <div class="mt-10 flex flex-col xl:flex-row jusitfy-center items-stretch w-full xl:space-x-8 space-y-4 md:space-y-6 xl:space-y-0">
    <div class="flex flex-col justify-start items-start w-full space-y-4 md:space-y-6 xl:space-y-8">
      <div class="flex flex-col justify-start items-start dark:bg-gray-800 bg-gray-50 px-4 py-4 md:py-6 md:p-6 xl:p-8 w-full">
        <p class="text-lg md:text-xl dark:text-white font-semibold leading-6 xl:leading-5 text-gray-800">Customer’s Cart</p>
           {% for order_item in order.items.all %}
        <div class="mt-4 md:mt-6 flex flex-col md:flex-row justify-start items-start md:items-center md:space-x-6 xl:space-x-8 w-full">
          <div class="pb-4 md:pb-8 w-full md:w-40">
              {% if order_item.item.image %}
            <img class="w-full hidden md:block" src="{{order_item.item.image.url}}" alt="product" />
            <img class="w-full md:hidden" src="{{order_item.item.image.url}}" alt="product" />
              {% endif %}
          </div>
          <div class="border-b border-gray-200 md:flex-row flex-col flex justify-between items-start w-full pb-8 space-y-4 md:space-y-0">
            <div class="w-full flex flex-col justify-start items-start space-y-8">
              <h3 class="text-xl dark:text-white xl:text-2xl font-semibold leading-6 text-gray-800">{{order_item.item.name}}</h3>

            </div>
            <div class="flex justify-between space-x-10 items-start w-full ml-10 ">
              <p class="text-base dark:text-white xl:text-lg leading-6 text-gray-800">Số lượng: {{order_item.quantity}}</p>
              <p class="text-base dark:text-white xl:text-lg font-semibold leading-6 text-gray-800">Thành tiền: {{order_item.get_item_total_formated}}</p>
            </div>
          </div>
        </div>
          {% endfor %}
        </div>

         <div class="flex justify-center flex-col md:flex-row flex-col items-stretch w-full space-y-4 md:space-y-0 md:space-x-6 xl:space-x-8">
        <div class="flex flex-col px-4 py-6 md:p-6 xl:p-8 w-full bg-gray-50 dark:bg-gray-800 space-y-6">
          <h3 class="text-xl dark:text-white font-semibold leading-5 text-gray-800">Tổng đơn</h3>
          <div class="flex justify-center items-center w-full space-y-4 flex-col border-gray-200 border-b pb-4">
            <div class="flex justify-between w-full">
              <p class="text-base dark:text-white leading-4 text-gray-800">Tạm tính</p>
              <p class="text-base dark:text-gray-300 leading-4 text-gray-600">{{order.get_order_total}}</p>
            </div>
            <div class="flex justify-between items-center w-full">
              <p class="text-base dark:text-white leading-4 text-gray-800">Shipping</p>
              <p class="text-base dark:text-gray-300 leading-4 text-gray-600">Free</p>
            </div>
          </div>
          <div class="flex justify-between items-center w-full">
            <p class="text-base dark:text-white font-semibold leading-4 text-gray-800">Tổng đơn</p>
            <p class="text-base dark:text-gray-300 font-semibold leading-4 text-gray-600">{{order.get_order_total}}</p>
          </div>
        </div>
      </div>
    </div>

    <div id="address_list" class="bg-gray-50 dark:bg-gray-200 w-full xl:w-96 flex justify-between items-center md:items-start px-4 py-6 md:p-6 xl:p-8 flex-col">
        <form id="addressForm" class="" method="POST" data-districts-url="{% url 'accounts:ajax-load-districts' %}" data-wards-url = "{% url 'accounts:ajax-load-wards' %}" novalidate>
           {% csrf_token %}
           {% if addresses %}
      <h3 class="text-xl dark:text-black font-semibold leading-5 text-gray-800">Customer</h3>
      <div class="flex flex-col md:flex-row xl:flex-col justify-start items-stretch h-full w-full md:space-x-6 lg:space-x-8 xl:space-x-0">
        <div class="flex flex-col justify-start items-start flex-shrink-0">

          <div class="flex justify-center w-full md:justify-start items-center space-x-4 py-8 border-b border-black">
            <img src="https://i.ibb.co/5TSg7f6/Rectangle-18.png" alt="avatar" />
            <div class="flex justify-start items-start flex-col space-y-2">

              <p class="text-base text-3xs dark:text-black font-semibold leading-4 text-left text-gray-800">{{user.first_name}} {{user.last_name}}</p>
              <p class="text-sm dark:text-black leading-5 text-gray-600">{{address.phone}}</p>
            </div>
          </div>

          <div class="flex justify-center text-gray-800 dark:text-black md:justify-start items-center space-x-4 py-4 border-b border-black w-full">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M19 5H5C3.89543 5 3 5.89543 3 7V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17V7C21 5.89543 20.1046 5 19 5Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M3 7L12 13L21 7" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            <p class="cursor-pointer text-sm leading-5 ">{{ user.email }}</p>
          </div>
        </div>
        <div class="flex justify-between xl:h-full items-stretch w-full flex-col mt-6 mb-10 mt-10">
          <div class="flex justify-center md:justify-start xl:flex-col flex-col md:space-x-6 lg:space-x-8 xl:space-x-0 space-y-4 xl:space-y-12 md:space-y-0 md:flex-row items-center md:items-start">
            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4 xl:mt-8">
              <p class="text-2xl dark:text-black font-semibold leading-4 text-center md:text-left text-gray-800">Địa chỉ giao hàng</p>

                <div class=" flex justify-start  p-2 ">
                     {% for address in addresses %}
                        <input id="user_address_{{address.id}}" name="address" value="{{address.id}}" type="radio" class="mt-4">
                        <label for="user_address_{{address.id}}" class="w-full">
                          <p class="text-xl ml-2 w-48 lg:w-full dark:text-black xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600">{{address.home}}{% if address.ward is not None %}
                                                    {{address.ward}}, {% endif %}
                                                    {{address.district}},
                                                    {{address.city}}</p>
                        </label>
                      </div>
            {% endfor %}
            </div>

            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4">
              <p class="text-2xl dark:text-black font-semibold leading-4 text-center md:text-left text-gray-800">Hình thức thanh toán</p>
                <div class="flex  md:justify-start items-center md:items-start flex-col ">
                        {% for value, name in form.fields.payment_option.choices %}
                        <input id="{{ name }}" {% if forloop.counter == 2 %} checked {% endif %} name="payment_option" value="{{ value }}" type="radio" class="" required>
                        <label class="text-xl w-48 lg:w-full dark:text-black xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600" for="{{ name }}">{{ name }}</label>

                </div>
            </div>
          </div>
             {% endfor %}
          <div class="flex w-full justify-center items-center md:justify-start md:items-start mt-24">
            <button class=" md:mt-0 dark:border-black dark:hover:bg-gray-200 dark:bg-transparent dark:text-black py-5 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 border border-gray-800 font-medium w-96 2xl:w-full text-base font-medium leading-4 text-gray-800">Đặt hàng</button>
          </div>
        </div>

      </div>
        {% endif %}
             </form>
    </div>
  </div>
</div>
{% endblock body_content %}
{% block script %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $('[name="city"]').change(function () {
    var url = $("#addressForm").attr("data-districts-url");
    var cityID = $(this).val(); 

    $.ajax({             
      url: url,
      data: {
        'city': cityID
      },
      success: function (data) {
        $("[name='district']").html(data);
        $("[name='ward']").html("<option value=''>---------</option>");
      }
    });

  });
</script>

<script>
    //select[name='district']
  $("[name='district']").change(function () {
    var url = $("#addressForm").attr("data-wards-url");
    var district_id = $(this).val();

    $.ajax({
      url: url,
      data: {
        'district': district_id
      },
      success: function (data) {
        $("[name='ward']").html(data);
      }
    });

  });
</script>

<script>
  $(document).ready(function() {
    $("#id_phone").keydown(function(event) {
        // Allow: backspace, delete, tab, escape, and enter
        if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || event.keyCode == 13 ||
            // Allow: Ctrl+A
            (event.keyCode == 65 && event.ctrlKey === true) ||
            // Allow: home, end, left, right
            (event.keyCode >= 35 && event.keyCode <= 39)) {
            // let it happen, don't do anything
            return;
        } else {
            // Ensure that it is a number and stop the keypress
            if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105)) {
                event.preventDefault();
            }
        }
    });
});
</script>
<script>
date = new Date();
year = date.getFullYear();
month = date.getMonth() + 1;
day = date.getDate();
hour = date.toLocaleTimeString();
document.getElementById("current_date").innerHTML = "Đơn hàng ngày: " + day + "/" + month + "/" + year + " lúc " + hour;
</script>
{% endblock script %}

accounts/templates/accounts/email_confirm.html
Xin chào {{name}}. Chúng tôi đã nhận được đơn hàng của bạn và tiến hành chuyển hàng trong thời gian sớm nhất.
Nếu bạn thanh toán bằng hình thức chuyển khoản, vui lòng chuyển tiền vào STK 100869677861 với cú pháp " Họ và tên + số điện thoại "
Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi

                        ----Dark Morty---

accounts/templates/accounts/user_info_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load static %}
{% block body_content %}
<div class="flex justify-center items-center md:mt-16">
    <form action="" method="post" class="bg-white border-black rounded-xl p-4">
        {% csrf_token %}
        {{form | crispy}}
        <input type="submit" class="border-2 border-black w-full bg-transparent hover:text-white hover:bg-black text-black p-4 m-4 md:m:0 xl:m-0 font-semibold rounded-full" value="Lưu">
    </form>
 </div>
{% endblock body_content %}

accounts/templates/accounts/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block body_content %}
<style>
    :root {
        --main-color: #4a76a8;
    }

    .bg-main-color {
        background-color: var(--main-color);
    }

    .text-main-color {
        color: var(--main-color);
    }

    .border-main-color {
        border-color: var(--main-color);
    }
</style>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>



<div class="bg-gray-100">


    <div class="container mx-auto my-5 p-5">
        <div class="md:flex no-wrap md:-mx-2 ">
            <!-- Left Side -->
            <div class="w-full md:w-3/12 md:mx-2">
                <!-- Profile Card -->
                <div class="bg-white p-3 border-t-4 border-green-400">
                    <div class="image overflow-hidden">
                        <img class="h-auto w-full mx-auto"
                            src="https://i.stack.imgur.com/l60Hf.png"
                            alt="">
                    </div>
                    <h1 class="text-gray-900 font-bold text-xl leading-8 my-1">{{user.first_name}} {{user.last_name}}</h1>
                </div>
                <!-- End of profile card -->
                <div class="my-4"></div>

            </div>
            <!-- Right Side -->
            <div class="w-full md:w-9/12 mx-2 h-64">
                <!-- Profile tab -->
                <!-- About Section -->
                <div class="bg-white p-3 shadow-sm rounded-sm">
                    <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                        <span class="text-green-500">
                            <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </span>
                        <span class="tracking-wide">About</span>
                    </div>
                    <div class="text-gray-700">
                        <div class="grid md:grid-cols-2 text-base  ">
                            <div class="grid grid-cols-3 border-b-2 border-blue-100">
                                <div class="px-4 py-2 font-semibold">First Name</div>
                                <div class="px-4 py-2">{{user.first_name}}</div>
                            </div>
                            <div class="grid grid-cols-3 border-b-2 border-blue-100">
                                <div class="px-4 py-2 font-semibold">Last Name</div>
                                <div class="px-4 py-2">{{user.last_name}}</div>
                            </div>
                             {% for address in address_list %}
                            <div class="grid grid-cols-3  border-b-2 border-blue-100">
                                <div class="px-4 py-2 font-semibold col-start-1">Số điện thoại {{ forloop.counter }}</div>
                                <div class="px-4 py-2">{{address.phone}}</div>
                            </div>
                            <div class="grid grid-cols-3">
                                <div class="px-4 py-2 font-semibold  border-b-2 border-blue-100">Địa chỉ {{ forloop.counter }}</div>
                                <div class="px-4 py-2 col-span-2  border-b-2 border-blue-100"> {{address.home}} {{address.ward}}, {{address.district}}, {{address.city}}</div>
                                <div class="px-4 py-2 place-self-start col-end-7 text-xs"><a href="{% url 'accounts:update-address' address.pk %}" class="border-b-2 pr-2 border-blue-300 hover:border-gray-500 ">Thay đổi</a>
                              <a href="{% url 'accounts:remove-address' address.pk %}" class=" border-b-2 border-blue-300 hover:border-gray-500">Xóa</a></div>

                            </div>
                              {% endfor %}

                            <div class="grid grid-cols-3  border-b-2 border-blue-100">
                                <div class="px-4 py-2 font-semibold ">Email</div>
                                <div class="px-4 py-2">
                                     {{user.email}}
                                </div>
                            </div>
                            <div class="px-4 py-2 place-self-end rounded-lg border-black hover:border-gray-500 bg-gray-200"> <a href="{% url 'accounts:new-address' %}" class="">Thêm địa chỉ</a></div>

                        </div>
                    </div>

                </div>
                <!-- End of about section -->

                <div class="my-4"></div>

                <!-- Experience and education -->

                    <!-- End of Experience and education grid -->

                <!-- End of profile tab -->
            </div>
        </div>
    </div>
</div>

{% endblock body_content %}