Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView, LoginView, LogoutView
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace="items")),
    path('accounts/', include('accounts.urls', namespace="accounts")),

    path('accounts/', include('allauth.urls')),

    # Password reset form
    path('password-reset/', PasswordResetView.as_view(template_name="registration/password_reset.html"),
         name="password_reset"),

    # Email sent success message
    path('password-reset-sent/', PasswordResetDoneView.as_view(template_name="registration/password_reset_sent.html"),
         name="password_reset_done"),

    # link to password reset page
    path('password-reset-confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
         name="password_reset_confirm"),

    # Pwd changed successfully message
    path('password-reset-completed/',
         PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
         name="password_reset_complete"),

]

items/urls.py
from django.conf.urls.static import static
from django.urls import path

from Ecommerce import settings
from .views import *

app_name = 'items'

urlpatterns = [
                  path('', HomeView.as_view(), name='home'),
                  path("chi-tiet-san-pham/<slug>/", ItemDetailView, name="details"),
                  path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
                  path('gio-hang/', CartView.as_view(), name='cart'),
                  path('tim-kiem/', item_search_view, name='search'),
                  path('danh-muc/<pk>', filter_by_category, name='filter-by-cate'),
                  path('remove-from-cart/<slug>/<size>', remove_from_cart, name='remove-from-cart'),
                  path('chi-tiet-don-hang/<pk>', OrderDetailView.as_view(), name='order-details'),
                  path('don-hang/', OrderListView.as_view(), name='orders'),
                  path('don-hang/dang-xu-ly/', OrderFilter, name='order-filter'),
                  path('don-hang/<state>', OrderFilter, name='order-filter'),
                  path('order-process-done/<pk>', OrderProcessDone, name='order-process-done'),
                  path('cancel-order/<pk>', cancel_order, name='cancel-order'),
                  path('remove-single-from-cart/<slug>/<size>/', remove_single_item_from_cart,
                       name='remove-single-from-cart'),
                  path('increase-quantity/<slug>/<size>/', increase_quantity, name='increase-quantity'),
                  path('aboutus', aboutus, name='aboutus'),
                  path('thanks', thanks, name='thanks')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/AboutUs.html
{% extends "base.html" %}
{% load static %}
{% block body_content %}
<!-- component -->
<div class="py-14 px-4 md:px-6 2xl:px-20 2xl:container 2xl:mx-auto">
  <!--- more free and premium Tailwind CSS components at https://tailwinduikit.com/ --->

  <div class="flex justify-start item-start space-y-2 flex-col">
    <h1 class="text-3xl dark:text-white lg:text-4xl font-semibold leading-7 lg:leading-9 text-gray-800">Order #13432</h1>
    <p class="text-base dark:text-gray-300 font-medium leading-6 text-gray-600">21st Mart 2021 at 10:34 PM</p>
  </div>
  <div class="mt-10 flex flex-col xl:flex-row jusitfy-center items-stretch w-full xl:space-x-8 space-y-4 md:space-y-6 xl:space-y-0">
    <div class="flex flex-col justify-start items-start w-full space-y-4 md:space-y-6 xl:space-y-8">
      <div class="flex flex-col justify-start items-start dark:bg-gray-800 bg-gray-50 px-4 py-4 md:py-6 md:p-6 xl:p-8 w-full">
        <p class="text-lg md:text-xl dark:text-white font-semibold leading-6 xl:leading-5 text-gray-800">Customer’s Cart</p>
        <div class="mt-4 md:mt-6 flex flex-col md:flex-row justify-start items-start md:items-center md:space-x-6 xl:space-x-8 w-full">
          <div class="pb-4 md:pb-8 w-full md:w-40">
            <img class="w-full hidden md:block" src="https://i.ibb.co/84qQR4p/Rectangle-10.png" alt="dress" />
            <img class="w-full md:hidden" src="https://i.ibb.co/L039qbN/Rectangle-10.png" alt="dress" />
          </div>
          <div class="border-b border-gray-200 md:flex-row flex-col flex justify-between items-start w-full pb-8 space-y-4 md:space-y-0">
            <div class="w-full flex flex-col justify-start items-start space-y-8">
              <h3 class="text-xl dark:text-white xl:text-2xl font-semibold leading-6 text-gray-800">Premium Quaility Dress</h3>
              <div class="flex justify-start items-start flex-col space-y-2">
                <p class="text-sm dark:text-white leading-none text-gray-800"><span class="dark:text-gray-400 text-gray-300">Style: </span> Italic Minimal Design</p>
                <p class="text-sm dark:text-white leading-none text-gray-800"><span class="dark:text-gray-400 text-gray-300">Size: </span> Small</p>
                <p class="text-sm dark:text-white leading-none text-gray-800"><span class="dark:text-gray-400 text-gray-300">Color: </span> Light Blue</p>
              </div>
            </div>
            <div class="flex justify-between space-x-8 items-start w-full">
              <p class="text-base dark:text-white xl:text-lg leading-6">$36.00 <span class="text-red-300 line-through"> $45.00</span></p>
              <p class="text-base dark:text-white xl:text-lg leading-6 text-gray-800">01</p>
              <p class="text-base dark:text-white xl:text-lg font-semibold leading-6 text-gray-800">$36.00</p>
            </div>
          </div>
        </div>
      </div>
      <div class="flex justify-center flex-col md:flex-row flex-col items-stretch w-full space-y-4 md:space-y-0 md:space-x-6 xl:space-x-8">
        <div class="flex flex-col px-4 py-6 md:p-6 xl:p-8 w-full bg-gray-50 dark:bg-gray-800 space-y-6">
          <h3 class="text-xl dark:text-white font-semibold leading-5 text-gray-800">Summary</h3>
          <div class="flex justify-center items-center w-full space-y-4 flex-col border-gray-200 border-b pb-4">
            <div class="flex justify-between w-full">
              <p class="text-base dark:text-white leading-4 text-gray-800">Subtotal</p>
              <p class="text-base dark:text-gray-300 leading-4 text-gray-600">$56.00</p>
            </div>
            <div class="flex justify-between items-center w-full">
              <p class="text-base dark:text-white leading-4 text-gray-800">Discount <span class="bg-gray-200 p-1 text-xs font-medium dark:bg-white dark:text-gray-800 leading-3 text-gray-800">STUDENT</span></p>
              <p class="text-base dark:text-gray-300 leading-4 text-gray-600">-$28.00 (50%)</p>
            </div>
            <div class="flex justify-between items-center w-full">
              <p class="text-base dark:text-white leading-4 text-gray-800">Shipping</p>
              <p class="text-base dark:text-gray-300 leading-4 text-gray-600">$8.00</p>
            </div>
          </div>
          <div class="flex justify-between items-center w-full">
            <p class="text-base dark:text-white font-semibold leading-4 text-gray-800">Total</p>
            <p class="text-base dark:text-gray-300 font-semibold leading-4 text-gray-600">$36.00</p>
          </div>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 dark:bg-gray-800 w-full xl:w-96 flex justify-between items-center md:items-start px-4 py-6 md:p-6 xl:p-8 flex-col">
      <h3 class="text-xl dark:text-white font-semibold leading-5 text-gray-800">Customer</h3>
      <div class="flex flex-col md:flex-row xl:flex-col justify-start items-stretch h-full w-full md:space-x-6 lg:space-x-8 xl:space-x-0">
        <div class="flex flex-col justify-start items-start flex-shrink-0">
          <div class="flex justify-center w-full md:justify-start items-center space-x-4 py-8 border-b border-gray-200">
            <img src="https://i.ibb.co/5TSg7f6/Rectangle-18.png" alt="avatar" />
            <div class="flex justify-start items-start flex-col space-y-2">
              <p class="text-base dark:text-white font-semibold leading-4 text-left text-gray-800">David Kent</p>
              <p class="text-sm dark:text-gray-300 leading-5 text-gray-600">10 Previous Orders</p>
            </div>
          </div>

          <div class="flex justify-center text-gray-800 dark:text-white md:justify-start items-center space-x-4 py-4 border-b border-gray-200 w-full">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M19 5H5C3.89543 5 3 5.89543 3 7V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17V7C21 5.89543 20.1046 5 19 5Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" />
              <path d="M3 7L12 13L21 7" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            <p class="cursor-pointer text-sm leading-5 ">david89@gmail.com</p>
          </div>
        </div>
        <div class="flex justify-between xl:h-full items-stretch w-full flex-col mt-6 md:mt-0">
          <div class="flex justify-center md:justify-start xl:flex-col flex-col md:space-x-6 lg:space-x-8 xl:space-x-0 space-y-4 xl:space-y-12 md:space-y-0 md:flex-row items-center md:items-start">
            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4 xl:mt-8">
              <p class="text-base dark:text-white font-semibold leading-4 text-center md:text-left text-gray-800">Shipping Address</p>
              <p class="w-48 lg:w-full dark:text-gray-300 xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600">180 North King Street, Northhampton MA 1060</p>
            </div>
            <div class="flex justify-center md:justify-start items-center md:items-start flex-col space-y-4">
              <p class="text-base dark:text-white font-semibold leading-4 text-center md:text-left text-gray-800">Billing Address</p>
              <p class="w-48 lg:w-full dark:text-gray-300 xl:w-48 text-center md:text-left text-sm leading-5 text-gray-600">180 North King Street, Northhampton MA 1060</p>
            </div>
          </div>
          <div class="flex w-full justify-center items-center md:justify-start md:items-start">
            <button class="mt-6 md:mt-0 dark:border-white dark:hover:bg-gray-900 dark:bg-transparent dark:text-white py-5 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-800 border border-gray-800 font-medium w-96 2xl:w-full text-base font-medium leading-4 text-gray-800">Edit Details</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body_content %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body_content %}

    <style>
        .work-sans {
            font-family: 'Work Sans', sans-serif;
        }

        #menu-toggle:checked + #menu {
            display: block;
        }

        .hover\:grow {
            transition: all 0.3s;
            transform: scale(1);
        }

        .hover\:grow:hover {
            transform: scale(1.02);
        }

        .carousel-open:checked + .carousel-item {
            position: static;
            opacity: 100;
        }

        .carousel-item {
            -webkit-transition: opacity 0.6s ease-out;
            transition: opacity 0.6s ease-out;
        }

        #carousel-1:checked ~ .control-1,
        #carousel-2:checked ~ .control-2,
        #carousel-3:checked ~ .control-3 {
            display: block;
        }

        .carousel-indicators {
            list-style: none;
            margin: 0;
            padding: 0;
            position: absolute;
            bottom: 2%;
            left: 0;
            right: 0;
            text-align: center;
            z-index: 10;
        }

        #carousel-1:checked ~ .control-1 ~ .carousel-indicators li:nth-child(1) .carousel-bullet,
        #carousel-2:checked ~ .control-2 ~ .carousel-indicators li:nth-child(2) .carousel-bullet,
        #carousel-3:checked ~ .control-3 ~ .carousel-indicators li:nth-child(3) .carousel-bullet {
            color: #000;
            /*Set to match the Tailwind colour you want the active one to be */
        }
    </style>



    <div>
    {% if page_obj.has_next %}
    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </div>
  <div class="loading" style="display: none;">
    Loading...
  </div>
    <!--Div infinite scroll-->


   <div class="carousel static container p-1 mx-auto mt-5 border-b-2 border-blue-200 z-1" style="max-width:1600px;">
        <div class="carousel-inner  overflow-hidden w-full">
            {% include 'slider.html' %}
        </div>
    </div>


    <section class="bg-white ">
  <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
        <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
            <nav id="store" class="w-full z-30 top-0 px-6 py-1  text-xl">
                <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 px-2 py-3">
                    <a class="uppercase tracking-wide no-underline hover:no-underline font-bold text-gray-800 text-3xl " href="#">
				Store
			        </a>
                    <div class="flex justify-center pr-60">

                         {% for cate in categories %}
                        <div class="group mr-4 block max-w-xs mx-auto rounded-lg p-3 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-sky-500 hover:ring-sky-500">
                       <a href="{% url 'items:filter-by-cate' cate.pk %}" class="p-2 group-hover:text-white text-xl font-semibold">
                          {{cate.name}}
                       </a>
                            </div>
                            {% endfor %}
                        </div>
                    <div class="flex items-center" id="store-nav-content text-2xl">
                        <button class="pl-3 inline-block no-underline hover:text-black">
                            <svg class="fill-current hover:text-black" xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24">
                                <path d="M7 11H17V13H7zM4 7H20V9H4zM10 15H14V17H10z" />
                            </svg>
                        </button>

               <div  id="searchBox" >
               <form action="{% url 'items:search' %}" method="POST">
                {% csrf_token %}


                 <div class="flex items-center max-w-md mx-auto bg-gray-200 rounded-lg ">
                     <div class="w-full">
                     <input id="searchBar" name="searchBar" type="search" class="w-full px-4 py-1 text-gray-800  focus:outline-none bg-gray-200"
                placeholder="search">
                    </div>
                 <div>
                <button  id="search" type="submit" class="flex items-center bg-blue-500 justify-center w-12 h-12 text-white rounded-r-lg"  >
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                    xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </button>
                 </div>
                </div>
            </form>
               </div>
               </div>
              </div>
            </nav>

                 {% for item in items %}

                    <div class="w-full md:w-1/3 xl:w-1/4 p-6 flex flex-col antialiased">

                  <a href="{% url 'items:details' item.slug %}" class="">
                        {% if item.image %}
                    <img class="hover:grow hover:shadow-lg" src="{{item.image.url}}">
                      {% endif %}
                    <div class="pt-3 flex items-center justify-between">
                        <p class="text-3xs font-bold">{{item.name}}</p>

                    </div>
                      {% if item.discount_price %}
                    <p class="pt-1 text-gray-900 ">
                         <del class="text-lg text-center text-red-500 font-semibold">{{item.item_formated_price}}</del><br>
                              <label class="text-xl  text-center text-black font-bold">{{item.item_formated_discount_price}}</label>

                              {% else %}
                              <label class="text-xl  text-center text-black font-bold">{{item.item_formated_price}}</label>
                             </p>
                       {% endif %}
                </a>
            </div>
             {% endfor %}
        </div>
  </div>
    </section>

{% endblock body_content %}
{% block script %}


<script>
  //Get the button
  var mybutton = document.getElementById("btnToTop");
  var mybutton2 = document.getElementById("btnToTop2");
  
  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function() {scrollFunction()};
  
  function scrollFunction() {
    if (document.body.scrollTop > 500 || document.documentElement.scrollTop > 500) {
      mybutton.style.display = "block";
      mybutton2.style.display = "block";
    } else {
      mybutton.style.display = "none";
      mybutton2.style.display = "none";
    }
  }
  
  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
  </script>

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script>
  <script>
    var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                // $('.loading').show();
            },
            onAfterPageLoad: function () {
                // $('.loading').hide();
            }
        });
  </script>
<script>
        $(function () {
            var availableTags = [
                {% for item in items %}
            "{{item.name}}",
            {% endfor %}
    ];
        $("#searchBar").autocomplete({
            source: availableTags
        });
  } );
    </script>
{% endblock script %}

templates/slider.html
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
  <script>
    var cont=0;
function loopSlider(){
  var xx= setInterval(function(){
        switch(cont)
        {
        case 0:{
            $("#slider-1").fadeOut(400);
            $("#slider-3").fadeOut(400);
            $("#slider-2").delay(400).fadeIn(400);
            $("#sButton1").removeClass("bg-gray-200");
            $("#sButton2").addClass("bg-gray-200");
        cont=1;

        break;
        }
        case 1:
        {

            $("#slider-2").fadeOut(400);
            $("#slider-3").delay(400).fadeIn(600);
            $("#sButton2").removeClass("bg-gray-200");
            $("#sButton3").addClass("bg-gray-200");

        cont=2;

        break;
        }
         case 2:
        {

            $("#slider-3").fadeOut(400);
            $("#slider-1").delay(400).fadeIn(400);
            $("#sButton3").removeClass("bg-gray-200");
            $("#sButton1").addClass("bg-gray-200");

        cont=0;
        break;
        }
        }},4000);

}

function reinitLoop(time){
clearInterval(xx);
setTimeout(loopSlider(),time);
}



function sliderButton1(){

    $("#slider-2").fadeOut(400);
    $("#slider-1").delay(400).fadeIn(400);
    $("#sButton2").removeClass("bg-gray-200");
    $("#sButton3").removeClass("bg-gray-200");
    $("#sButton1").addClass("bg-gray-200");
    reinitLoop(4000);
    cont=0

    }

    function sliderButton2(){
    $("#slider-1").fadeOut(400);
    $("#slider-3").fadeOut(400);
    $("#slider-2").delay(400).fadeIn(400);
    $("#sButton1").removeClass("bg-gray-200");
    $("#sButton3").removeClass("bg-gray-200");
    $("#sButton2").addClass("bg-gray-200");
    reinitLoop(4000);
    cont=1

    }

    function sliderButton3(){
    $("#slider-2").fadeOut(400);
    $("#slider-1").fadeOut(400);
    $("#slider-3").delay(400).fadeIn(400);
    $("#sButton2").removeClass("bg-gray-200");
    $("#sButton1").removeClass("bg-gray-200");
    $("#sButton3").addClass("bg-gray-200");
    reinitLoop(4000);
    cont=2

    }

    $(window).ready(function(){
        $("#slider-2").hide();
        $("#slider-3").hide();
        $("#sButton1").addClass("bg-gray-200");

        loopSlider();

    })

  </script>


<div class="carousel relative container mx-auto mt-5 h-screen" style="max-width:1600px;">
    <div class="carousel-inner relative overflow-hidden w-full">
      <div id="slider-1" class="container mx-auto ">
        <div class="block h-screen w-full bg-center flex bg-cover text-white pt-24 pb-80 px-10 object-fill" style="background-image: url(https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1932)"></div>
      </div>

      <br>
      <div id="slider-2" class="container mx-auto  ">
        <div class="bg-cover bg-center h-screen text-white pt-24 pb-80 px-10 object-fill" style="background-image: url(https://images.unsplash.com/photo-1593642634315-48f5414c3ad9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80)"></div>
      </div>
  </div>
    <br>
       <div id="slider-3" class="container mx-auto  ">
        <div class="bg-cover bg-center h-screen text-white pt-24 pb-80 px-10 object-fill" style="background-image: url(https://images.unsplash.com/photo-1559163179-3fd017552229?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170)"></div>
      </div>
  </div>
      <br>

 <div  class="flex justify-between w-20 mx-auto space-x-2  pb-2 mt-3 ">
        <button id="sButton1" onclick="sliderButton1()" class="bg-black rounded-full w-4 pb-2 "></button>
        <button id="sButton2" onclick="sliderButton2() " class="bg-black rounded-full w-4 p-2 "></button>
        <button id="sButton3" onclick="sliderButton3() " class="bg-black rounded-full w-4 p-2 "></button>
  </div>

templates/thanks.html
{% extends "base.html" %}
{% load static %}
{% block body_content %}
<div class="bg-white p-6  md:mx-auto">
        <svg viewBox="0 0 24 24" class="text-green-600 w-16 h-16 mx-auto my-6">
            <path fill="currentColor"
                d="M12,0A12,12,0,1,0,24,12,12.014,12.014,0,0,0,12,0Zm6.927,8.2-6.845,9.289a1.011,1.011,0,0,1-1.43.188L5.764,13.769a1,1,0,1,1,1.25-1.562l4.076,3.261,6.227-8.451A1,1,0,1,1,18.927,8.2Z">
            </path>
        </svg>
        <div class="text-center">
            <h3 class="md:text-2xl text-base text-gray-900 font-semibold text-center">Mua hàng thành công</h3>
            <p class="text-gray-600 my-2">Đơn hàng của bạn đã được tiếp nhận. Chúng tôi sẽ liên lạc với bạn trong thời gian sớm nhất</p>
            <p> Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!  </p>
            <div class="py-10 text-center">
                <a href="{% url 'items:home' %}" class="px-12 bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-3">
                   Quay lại mua sắm
               </a>
            </div>
        </div>
    </div>
{% endblock body_content %}